app = "simobi-mqtt-bridge"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  DEFAULT_ACCURACY = "10"
  MQTT_TOPIC = "buggy/+/data"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
